// Copyright 2015 the pokefans authors. See copying.md for legal info
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokefans.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.system_permission_log = new HashSet<PermissionLogEntry>();
            this.system_permissions1 = new HashSet<Permission>();
            this.system_user_permissions = new HashSet<UserPermission>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string friendly_name { get; set; }
        public Nullable<int> metapermission_id { get; set; }
    
        public virtual ICollection<PermissionLogEntry> system_permission_log { get; set; }
        public virtual ICollection<Permission> system_permissions1 { get; set; }
        public virtual Permission system_permissions2 { get; set; }
        public virtual ICollection<UserPermission> system_user_permissions { get; set; }
    }
}
