
// Copyright 2015 the pokefans authors. See copying.md for legal info
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pokefans.Data
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.system_permission_log = new HashSet<PermissionLogEntry>();

        this.system_permission_log1 = new HashSet<PermissionLogEntry>();

        this.Logins = new HashSet<UserLogin>();

        this.system_user_permissions = new HashSet<UserPermission>();

    }


    public int id { get; set; }

    public string Name { get; set; }

    public System.DateTime Registered { get; set; }

    public string RegisteredIp { get; set; }

    public string Url { get; set; }

    public sbyte Status { get; set; }

    public string BanReason { get; set; }

    public Nullable<System.DateTime> BanTime { get; set; }

    public string Rank { get; set; }

    public string Color { get; set; }

    public Nullable<short> UnreadNotificationCount { get; set; }

    public string Password { get; set; }

    public string Salt { get; set; }

    public string Activationkey { get; set; }

    public string Email { get; set; }



    public virtual ICollection<PermissionLogEntry> system_permission_log { get; set; }

    public virtual ICollection<PermissionLogEntry> system_permission_log1 { get; set; }

    public virtual ICollection<UserLogin> Logins { get; set; }

    public virtual ICollection<UserPermission> system_user_permissions { get; set; }

}

}
