// Copyright 2015 the pokefans authors. See copying.md for legal info
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokefans.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int id { get; set; }
        public System.DateTime time { get; set; }
        public string ip { get; set; }
        public int user_id { get; set; }
        public sbyte success { get; set; }
        public string reason { get; set; }
    
        public virtual User system_users { get; set; }
    }
}
